### ISSUE TITLE
Integrate Summary Contaminant Info too?

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/benthic-dash#1]
Anyway to integrate some of the sum pollutant concentrations of interest into the dashboard, as well? E.g., Total PCBs, Total DDT, Sum LMW PAHs, Sum HMW PAHs, and Total PAHs? They should all have associated TEL/PEL criteria too. It looks like you captured Total Chlordane, but the others don't appear in the dropdown (AFAIK).

**Comment by fawda123** [comment]
Good call, I had to include those summaries in the overall PEL ratios (https://github.com/tbep-tech/tbeptools/blob/75dc8bba4bd4fcf436b1e942f3bfe3ffba037802/R/anlz_sedimentpel.R#L74), but there's currently no way to view them separately.  This would be a good feature to add to tbeptools.

**Comment by fawda123** [comment]
@esherwoo77 done, see here https://shiny.tbep.org/benthic-dash/#section-sediment-contaminants, select Organics > Total PAH, etc.
